### ISSUE TITLE
perturbation process confusion

### ISSUE THREAD

**Issue by Peg-Wu** [MehrshadSD/Fatecode#1]
![image](https://github.com/user-attachments/assets/91ac2511-2be8-4ee1-b683-094ae3b4a0b2)

Hi, developer!
Thanks for your great work! Why use empty[39] to predict decoder output but empty[79] to predict cell type?

Peng

**Comment by MehrshadSD** [comment]
Hi Peng,

Thank you for pointing that out. Since varying hyperparameters result in different node perturbations, I overlooked updating that section of the GitHub code. I'm currently working on a more polished and user-friendly version of the code, and I hope to have it ready soon.

**Comment by Peg-Wu** [comment]
Thank you for your positive reply. I have another question, may I ask whether the gene score should be sorted by absolute value, positive and negative numbers can indicate up-regulation and down-regulation of genes respectively？

Thanks,
Peng

**Comment by MehrshadSD** [comment]
Hi Peng,

Apologies for the delayed response, I’ve been quite busy lately. As we highlighted in the paper: "M does not explicitly define the extent to which each gene should be perturbed to achieve target B. However, it provides insights into the genes crucial for transitioning the cell type distribution from the initial state A to the desired state B"

I should also note that training an AE can be challenging, as the outcomes are highly dependent on selecting the appropriate hyperparameters (e.g., the number of layers, nodes, and activation functions). Stefan Bauer has an excellent lecture on this topic, which I highly recommend.

**Comment by Peg-Wu** [comment]
Hello Friend,

I have another question to ask you.

The perturbation range of the latent variable is [0.5, 10], and the step size is 0.5. Can this perturbation range be set larger? Or rather, why is the disturbance range set to [0.5, 10]? What are the specific considerations?

Thanks,
Peng
